spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: WARN
    '[org.flywaydb.core]': INFO
    '[org.springframework]': INFO
    '[com.example.m450]': INFO