spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: ${SERVER_PORT:8080}

debug: false

logging:
  level:
    root: INFO
    '[org.flywaydb.core]': DEBUG
    '[org.springframework]': DEBUG
    '[com.example.m450]': DEBUG