ALTER TABLE airline ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE aircraft ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE passenger ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE flight ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE seat ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;