name: Java CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

env:
  MAVEN_OPTS: "-Dmaven.repo.local=$GITHUB_WORKSPACE/.m2/repository -Dmaven.install.skip=true"
  MAVEN_CLI_OPTS: "--batch-mode --no-transfer-progress"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, prod]
        include:
          - environment: dev
            profile: dev
            version_prefix: DEV-BUILD
          - environment: prod
            profile: prod
            version_prefix: PROD-BUILD
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
        cache-dependency-path: '**/pom.xml'
    
    - name: Build
      run: |
        VERSION="${{ matrix.version_prefix }}-${GITHUB_SHA::7}"
        if [[ "${{ matrix.environment }}" == "prod" && "${{ github.ref_type }}" == "tag" ]]; then
          VERSION="${{ github.ref_name }}"
        fi
        ./mvnw ${{ env.MAVEN_CLI_OPTS }} clean package -P${{ matrix.profile }} -DskipTests -Dversion=$VERSION
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-${{ matrix.environment }}
        path: target/*.jar
        retention-days: 5

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
        cache-dependency-path: '**/pom.xml'
    
    - name: Run tests
      run: |
        ./mvnw ${{ env.MAVEN_CLI_OPTS }} test
        echo "Total Coverage $(cat target/site/jacoco/index.html | grep -o 'Total[^%]*%' | sed -n 's/.*Total.*>\(.*\)%/\1/p')%"
    
    - name: Publish Test Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          target/surefire-reports/TEST-*.xml
          target/site/jacoco/jacoco.xml
        retention-days: 5
